-- TOEIC 단어 데이터 복원 (toeicword.csv 기반)

-- 기존 TOEIC 데이터 삭제
DELETE FROM word_categories WHERE word_id IN (SELECT id FROM words WHERE category = 'toeic');
DELETE FROM words WHERE category = 'toeic';

-- TOEIC 단어 INSERT (ID는 자동 증가하므로 생략)
INSERT INTO words (english, korean, category) VALUES
('knowledgeable', 'ad . ( 사람 수식 ) 아는 것이 많은 . 잘 아는', 'toeic'),
('recognize', 'v . ( 공로 를 ) 인정 하다 : 알아 보다', 'toeic'),
('updated', 'adj . 최신 의 , 업데이트 된', 'toeic'),
('provide', 'v . 제공 하다 . 주다', 'toeic'),
('regulation', 'n . 규제 , 규정', 'toeic'),
('precisely', 'adv . 정확히', 'toeic'),
('perspective', 'n . 관점 , 견해 시각', 'toeic'),
('knowledgeably', 'adv . 박식 하게', 'toeic'),
('knowledge', 'n . 지식 ( 불가 산 명사 ) : 이해 ( 가산 명사 )', 'toeic'),
('honor', '명예 를 주다', 'toeic'),
('realize', '인식 하다 확실히 이해 하다', 'toeic'),
('recognition', 'n . 알아 봄 , 인식 , 인정', 'toeic'),
('recognizable', 'adj . 인식 할 수 있는 , 알아볼 수 있는', 'toeic'),
('be recognized for', '~로 인정 받다', 'toeic'),
('be credited with', '~로 인정 받다', 'toeic'),
('in recognition of', '~를 인정하여', 'toeic'),
('advertising agency', '광고 업체', 'toeic'),
('approaching date', '다가오는 날짜', 'toeic'),
('approaching storm', '다가오는 폭풍', 'toeic'),
('boarding ticket', '탑승권', 'toeic'),
('challenging task', '힘든 과제', 'toeic'),
('connecting flight', '연결편', 'toeic'),
('declining demand', '감소 하는 수요', 'toeic'),
('demanding boss', '까다로운 / 힘든 상사', 'toeic'),
('differing/varying opinion', '차이 가 나는 의견', 'toeic'),
('developing country', '| 개발 도상국가', 'toeic'),
('emerging technology', '| 떠오르는 기술', 'toeic'),
('emerging market/company', '신흥 시장 / 회사', 'toeic'),
('encouraging remark', '격려 의 / 고무 적인 말', 'toeic'),
('existing equipment', '기존 장비', 'toeic'),
('increasing pressure', '증가 하는 압력', 'toeic'),
('lasting effect/memory', '지속적인 효과 / 기억', 'toeic'),
('accomplished mission/musician', '성취 된 미션 / 숙달 된 음악가', 'toeic'),
('attached document', '첨부 된 문서', 'toeic'),
('celebrated landmarks', '유명한 관광 명소', 'toeic'),
('classified ad', '구인 [ 구직 ] 광고', 'toeic'),
('combined efforts', '결합 된 노력', 'toeic'),
('completed form', '작성된 양식 / 문서', 'toeic'),
('customized/personalized products', '주문 제작 / 맞춤형 제품', 'toeic'),
('damaged items', '손상된 물건', 'toeic'),
('designated area/spots', '지정된 지역 / 장소', 'toeic'),
('detailed information', '자세한 정보', 'toeic'),
('dedicated/devoted/committed staff', '헌신적인 직원', 'toeic'),
('developed country', '선진국', 'toeic'),
('disabled/handicapped people', '장애인', 'toeic'),
('distinguished/renowned architect', '뛰어난 / 유명한 건축가', 'toeic'),
('enclosed document', '동봉 된 문서', 'toeic'),
('enclosed parking garage', '실내 주차장', 'toeic'),
('lasting impression', '지속적인 인상', 'toeic');
