-- TOEIC 단어 데이터 복원 (toeicword.csv 기반)

-- 기존 TOEIC 데이터 삭제
DELETE FROM word_categories WHERE word_id IN (SELECT id FROM words WHERE category = 'toeic');
DELETE FROM words WHERE category = 'toeic';

-- TOEIC 단어 INSERT
INSERT INTO words (english, korean, category) VALUES
('knowledgeable', 'ad . ( 사람 수식 ) 아는 것이 많은 . 잘 아는', 'toeic'),
('recognize', 'v . ( 공로 를 ) 인정 하다 : 알아 보다', 'toeic'),
('updated', 'adj . 최신 의', 'toeic'),
('provide', 'v . 제공 하다 . 주다', 'toeic'),
('regulation', 'n . 규제', 'toeic'),
('precisely', 'adv . 정확히', 'toeic'),
('perspective', 'n . 관점', 'toeic'),
('knowledgeably', 'adv . 박식 하게', 'toeic'),
('knowledge', 'n . 지식 ( 불가 산 명사 ) : 이해 ( 가산 명사 )', 'toeic'),
('honor', '명예 를 주다', 'toeic'),
('realize', '인식 하다 확실히 이해 하다', 'toeic'),
('recognition', 'n . 알아 봄', 'toeic'),
('recognizable', 'adj . 인식 할 수 있는', 'toeic'),
('be recognized for', '~로 인정 받다', 'toeic'),
('be credited with', '~로 인정 받다', 'toeic'),
('in recognition of', '~를 인정하여', 'toeic'),
('advertising agency', '광고 업체', 'toeic'),
('approaching date', '다가오는 날짜', 'toeic'),
('approaching storm', '다가오는 폭풍', 'toeic'),
('boarding ticket', '탑승권', 'toeic'),
('challenging task', '힘든 과제', 'toeic'),
('connecting flight', '연결편', 'toeic'),
('declining demand', '감소 하는 수요', 'toeic'),
('demanding boss', '까다로운 / 힘든 상사', 'toeic'),
('differing/varying opinion', '차이 가 나는 의견', 'toeic'),
('developing country', '| 개발 도상국가', 'toeic'),
('emerging technology', '| 떠오르는 기술', 'toeic'),
('emerging market/company', '신흥 시장 / 회사', 'toeic'),
('encouraging remark', '격려 의 / 고무 적인 말', 'toeic'),
('existing equipment', '기존 장비', 'toeic'),
('increasing pressure', '증가 하는 압력', 'toeic'),
('lasting effect/memory', '지속적인 효과 / 기억', 'toeic'),
('accomplished mission/musician', '성취 된 미션 / 숙달 된 음악가', 'toeic'),
('attached document', '첨부 된 문서', 'toeic'),
('celebrated landmarks', '유명한 관광 명소', 'toeic'),
('classified ad', '구인 [ 구직 ] 광고', 'toeic'),
('combined efforts', '결합 된 노력', 'toeic'),
('completed form', '작성된 양식 / 문서', 'toeic'),
('customized/personalized products', '주문 제작 / 맞춤형 제품', 'toeic'),
('damaged items', '손상된 물건', 'toeic'),
('designated area/spots', '지정된 지역 / 장소', 'toeic'),
('detailed information', '자세한 정보', 'toeic'),
('dedicated/devoted/committed staff', '헌신적인 직원', 'toeic'),
('developed country', '선진국', 'toeic'),
('disabled/handicapped people', '장애인', 'toeic'),
('distinguished/renowned architect', '뛰어난 / 유명한 건축가', 'toeic'),
('enclosed document', '동봉 된 문서', 'toeic'),
('enclosed parking garage', '실내 주차장', 'toeic'),
('lasting impression', '지속적인 인상', 'toeic'),
('leading company', '일류 / 선도 하는 회사', 'toeic'),
('missing luggage (=misplaced', 'lost)', 'toeic'),
('monitoring system', '검열 체계', 'toeic'),
('neighboring area', '인근 지역', 'toeic'),
('ongoing matter', '진행중인 일', 'toeic'),
('opening/closing remarks', '개회사 / 폐회사', 'toeic'),
('ordering procedures', '주문 절차', 'toeic'),
('pressing matter', '긴박한 문제', 'toeic'),
('promising member', '유망한 회원', 'toeic'),
('promising location', '유망한 장소', 'toeic'),
('recurring problem', '반복 하는 문제', 'toeic'),
('remaining work/employees', '남은 일 / 직원 들', 'toeic'),
('rewarding effort', '보람 있는 노력', 'toeic'),
('rising/increasing cost', '증가 하는 비용', 'toeic'),
('surrounding area', '주변 환경', 'toeic'),
('striking agreement', '인상적인 합의', 'toeic'),
('overwhelming order', '압도적 인 주문', 'toeic'),
('presiding officer', '사회자', 'toeic'),
('weakening economy', '경제 약세', 'toeic'),
('widening gap', '큰 격차', 'toeic'),
('convincing argument', '설득력 있는 주장', 'toeic'),
('estimated arrival time', '도착 예정 시간', 'toeic'),
('estimated delivery date', '예상 배송일', 'toeic'),
('extended working hours', '연장 근무 시간', 'toeic'),
('established company', '확고한 중견 기업', 'toeic'),
('experienced people', '능숙한 사람', 'toeic'),
('featured article/speaker', '특집 기사 / 특별 연사', 'toeic'),
('featured attraction/spot', '특징 이 되는 장소', 'toeic'),
('finished product', '완제품', 'toeic'),
('guided tour', '가이드 여행', 'toeic'),
('handcrafted piece', '수 제품', 'toeic'),
('limited warranty/items/time', '보증 제한 / 제한된 품목 / 시간', 'toeic'),
('newly purchased item', '새롭게 구입 한 IT', 'toeic'),
('newly appointed C.E.O.', '새롭게 임명 된C.E.O.', 'toeic'),
('preferred means', '선호 되는 수단', 'toeic'),
('proposed/suggested plan', '제안 된 계획', 'toeic'),
('processed foods', '가공 식품', 'toeic'),
('recycled paper', '재활용 종이', 'toeic'),
('qualified applicant', '적격 인 지원자', 'toeic'),
('selected candidate', '선택된 후보', 'toeic'),
('skilled/experienced/seasoned', '숙련 된 직원', 'toeic'),
('unbiased advice', '편견 없는 조언', 'toeic'),
('updated version/line', '업데이트 된 버전 / 제품군', 'toeic'),
('valued customer', '가치 있는 고객', 'toeic'),
('written consent/permission', '서면 동의 / 허가', 'toeic'),
('written exam', '필기 시험', 'toeic'),
('be busy - ing', '~ 하느라 바쁘다', 'toeic'),
('be worth - ing', '~ 할 가치 가 있다', 'toeic'),
('feel like - ing', '~ 하고 싶어 하다', 'toeic'),
('refrain from - ing', '삼가다', 'toeic'),
('spend 시간 / 돈 ing', '~ 하는 데 ( 시간 / 돈 ) 을 쓰다', 'toeic'),
('prevent prohibit 목 rom - ing', '- 하는 것을 막다', 'toeic'),
('have trouble difficulty ing', '- 하는 데 어려움 을 겪다', 'toeic'),
('prior to N / Hing', '~ 하기 전에', 'toeic'),
('on ( upon ] N / -ing', '~ 하자마자', 'toeic'),
('by - ing', '~ 함으로써', 'toeic'),
('in -ing', '- 함에 있어서', 'toeic'),
('for N / -ing', '~ 를 위해', 'toeic'),
('be used to N/-ing', '~에 익숙하다', 'toeic'),
('be accustomed to N/-ing', '~에 익숙하다', 'toeic'),
('be familiar with', '~에 익숙하다', 'toeic'),
('be devoted/dedicated/committed to N/-ing', '~에 전념 헌신 기여하다', 'toeic'),
('contribute to N/-ing', '~에 기여하다', 'toeic'),
('be opposed to N/-ing', '~에 반대하다', 'toeic'),
('object to N/-ing', '~에 반대하다', 'toeic'),
('oppose N/-ing', '~에 반대하다', 'toeic'),
('be subject to N/-ing', '~ 의 대상이다 ~의 영향을 받기 쉽다', 'toeic'),
('be capable of N/-ing', '~할 수 있다', 'toeic'),
('be resistant to N/-ing', '~에 저항하다 강하다', 'toeic'),
('look forward to N/-ing', '~를 기대하다', 'toeic'),
('reply/respond/react to N/-ing', '~에 응답하다 반응하다', 'toeic'),
('lead to N / -ing', '~ 를 초래 하다 . 야기 하다', 'toeic'),
('object to N / -ing', '~ 에 반대 하다', 'toeic'),
('contribute to N / -ing', '~ 에 기여 하다', 'toeic'),
('aporeciate -ing', '감사 하다', 'toeic'),
('consider - ing', '고려 하다', 'toeic'),
('suggest -ing', '제안 하다', 'toeic'),
('recommend - ing', '추천 하다', 'toeic'),
('advise - ing', '조언', 'toeic'),
('include -ing', '포함 하다', 'toeic'),
('involve -ing', '포함 하다', 'toeic'),
('keep - ing', '계속 하다', 'toeic'),
('practice - ing', '연습 하다', 'toeic'),
('enjoy -ing', '즐기다', 'toeic'),
('admit - ing', '인정 하다', 'toeic'),
('deny - ing', '부인 하다', 'toeic'),
('postpone -ing', '연기하다', 'toeic'),
('put off -ing', '연기하다', 'toeic'),
('put off-ing', '연기하다', 'toeic'),
('discontinue(=quit) -ing', '중단하다', 'toeic'),
('finish -ing', '끝내다', 'toeic'),
('stop -ing', '멈추다', 'toeic'),
('dislike - ing', '싫어 하다', 'toeic'),
('mind -ing', '꺼리다', 'toeic'),
('avoid -ing', '피하다', 'toeic'),
('give up - ing', '포기 하다', 'toeic'),
('resist - ing', '저항 하다', 'toeic'),
('advertising', '광고 ( 업 )', 'toeic'),
('boarding', '탑승', 'toeic'),
('spending', '지출', 'toeic'),
('funding', '자금 조달', 'toeic'),
('accounting', '회계', 'toeic'),
('housing', '주택 ( 공급 )', 'toeic'),
('planning', '계획', 'toeic'),
('cleaning', '청소', 'toeic'),
('widening', '확장', 'toeic'),
('processing', '처리 / 절차 / 가공', 'toeic'),
('hearing', '청각 / 공청회', 'toeic'),
('pricing', '가격 책정', 'toeic'),
('opening', '공석', 'toeic'),
('staffing', '직원 배치', 'toeic'),
('training', '훈련', 'toeic'),
('sightseeing', '관광', 'toeic'),
('ability to V', '- 할 수 있는 능력', 'toeic'),
('plan to V', '- 할 계획', 'toeic'),
('initiative to V', '- 할 계획', 'toeic'),
('effort to V', '하기 위한 노력', 'toeic'),
('way to V', '- 할 방법', 'toeic'),
('discussion to V', '- 할 수 있다', 'toeic'),
('be about to v', '막 ~ 하려고 하다', 'toeic'),
('be willing to V', '기꺼이 ~ 하다', 'toeic'),
('be eligible/entitled/qualified to V', '할 자격 이 있다', 'toeic'),
('encouraged/urged to V', '~ 하도록 권고되다', 'toeic'),
('concentrate', 'v . 집중 하다', 'toeic'),
('concentrated', '농축 된 : 밀집된', 'toeic'),
('concentration', '집중', 'toeic'),
('concentrative', '집중적인', 'toeic'),
('concentration on sth', '정신 집중 / ( 노력 등 의 ) 집중', 'toeic'),
('concentration of sth', '( 무엇이 한 곳에 모이는 ) 집중', 'toeic'),
('outline', 'v . 윤곽 을 나타내 다 . 개요 를 서술 하다 n . 개요', 'toeic'),
('quarterly sales', '분기 별 매출', 'toeic'),
('attire', '의복', 'toeic'),
('result', 'n . 결과 v.- 로부터 발생 하다 ( from ) : - 을 초래 하다 ( in )', 'toeic'),
('as a result of', '- 의 결과 원인', 'toeic'),
('release survey results', '설문 결과 를 공개 하다', 'toeic'),
('result in 결과', '~ 을 초래 하다', 'toeic'),
('lead to 결과', '~ 을 초래 하다', 'toeic'),
('cause 결과', '~ 을 초래 하다', 'toeic'),
('result from 원인', '- 로부터 발생 하다', 'toeic'),
('markedly', 'adv . 현저 하게', 'toeic'),
('soak', 'v.- 을 홈뻑 적시다', 'toeic'),
('indefinitely', 'adv . 무 ( 기 ) 한 으로', 'toeic'),
('managerial', '관리 의', 'toeic'),
('relocate', '이전 하다', 'toeic'),
('relocation', '재배치', 'toeic'),
('delay', 'n . 지연', 'toeic'),
('eligible', 'adj . 자격 이 있는', 'toeic'),
('eligibility', 'n . 적임', 'toeic'),
('candidate', 'n . 지원자', 'toeic'),
('enforce', 'v . 강요 하다 ; 시행 하다', 'toeic'),
('distributor', 'n . 유통 업자 [ 체 ]', 'toeic'),
('distribute', 'v . 배포 하다 . 배급 하다', 'toeic'),
('distribution', 'n . 배포', 'toeic'),
('distributive', 'adj . ( 상품 ) 유통 의', 'toeic'),
('distribute A to B', 'A 를 B 에게 배포 하다', 'toeic'),
('costly', 'adj . 비용 이 많이 드는', 'toeic'),
('leisurely', '한가로운', 'toeic'),
('likely', '가능성 있는', 'toeic'),
('timely', '시기 적절한', 'toeic'),
('credential', 'n . 홀륭 한 경력', 'toeic'),
('be given preference', 'phr . 우대 를 받다', 'toeic'),
('issue', 'v . 지급 ( 발급 ] 하다', 'toeic'),
('diligently', 'adv . 부지런히', 'toeic'),
('critical', 'adj . 대단히 중요한 : 비판적인', 'toeic'),
('supplement', 'v . 보충 ( 추가 ] 하다 n 보충 ( 추가 ] ( 물 ) : ( 책 의 ) 부록 : ( 신문 의 ) 증보판', 'toeic'),
('supplementary', 'adj . 보충 의', 'toeic'),
('profile', 'v . 프로필 을 알려주 다 ( 작성 하다 ] n . 측면 : 프로필', 'toeic'),
('keep [ maintain ] a low profile', '겸손 함 을 유지 하다 . 몸 을 사리다', 'toeic'),
('reportedly', 'adv . 보도 에 의하면', 'toeic'),
('appointee', 'n . 지명 된 사람', 'toeic'),
('appointment', 'n . 임명', 'toeic'),
('appointment', 'n . 임명', 'toeic'),
('incorporate', '일부로 포함 하다', 'toeic'),
('incorporation', 'n . 포함 법인 설립', 'toeic'),
('incorporated', 'adj . 법인 조직의', 'toeic'),
('adjacent', 'adj . ( 지역 · 건물 등 이 ) 인접한 . 가까운', 'toeic'),
('adjacent to 장소', '- 에 인접한', 'toeic'),
('personnel', 'n . 직원 들', 'toeic'),
('occupancy', 'n . 사용', 'toeic'),
('colleague', 'n . 동료', 'toeic'),
('on-call', 'adj 대기 중인 ( 전화 만 하면 언제든지 달려가 는 )', 'toeic'),
('maintenance', 'n . 보수 관리', 'toeic'),
('maintain', 'v . 유지 하다 . 보수 하다', 'toeic'),
('committed', 'ad . 헌신적 인', 'toeic'),
('commitment', 'n . 전념', 'toeic'),
('be committed[dedicated/devoted) to', '~에 기여하다 헌신하다', 'toeic'),
('simplify', 'v . 간소화 하다', 'toeic'),
('retrieve', 'v . 되찾다 . 회수 하다 : 정보 를 검색 하다', 'toeic'),
('retrieve luggage', '수화물 ( 짐 ) 을 찾다', 'toeic'),
('agreement', 'n . 동의', 'toeic'),
('in agreement of', '~ 에 동의 하는', 'toeic'),
('expedite', 'v . 신속히 처리 하다 . 진척 시키다', 'toeic'),
('expeditious', 'adj . 신속한', 'toeic'),
('culinary', 'adj 요리의', 'toeic'),
('destination', 'n . 행선지', 'toeic'),
('assortment', 'n . 모음', 'toeic'),
('an assortment of 복수 명사', '여러 가지의', 'toeic'),
('unanimous', 'adj . 만장일치의', 'toeic'),
('encouragement', 'n . 격려', 'toeic'),
('encourage 목적어 to V', '- 하도록 권장 하다 장려 하다', 'toeic'),
('be encouraged to V', '- 하도록 권장 받다', 'toeic'),
('easily', 'adv . 쉽게', 'toeic'),
('normally', 'adv . 일반적 으로', 'toeic'),
('past', 'prep . 지나서 adj . 지난', 'toeic'),
('nomalize', 'v . 정상화 되다', 'toeic'),
('normality', 'n . 정상 상태', 'toeic'),
('conveniently', 'adv . 편리 하게', 'toeic'),
('review', 'v . 검토 하다', 'toeic'),
('promising', 'adv . 유망한', 'toeic'),
('reputation', 'n . 평판', 'toeic'),
('permission', 'n . 허가', 'toeic'),
('be bound to V', 'phr . 틀림 없이 / 반드시 ~ 할 것이다', 'toeic'),
('enhance', 'v . 향상 시키다 . 강화 하다', 'toeic'),
('enroll', 'v . 등록 하다', 'toeic'),
('associate', 'n . ( 사업 / 직장 ) 동료 : 직원 v . 관련 시키다', 'toeic'),
('enclosed', 'adj . 동봉 된 : 둘러싸인', 'toeic'),
('feature', 'v . ~ 을 특징 으로 하다', 'toeic'),
('characteristic', 'n . 특징', 'toeic'),
('whereas', '반면에', 'toeic'),
('distribution', 'n . 배포', 'toeic'),
('specifics', 'n . 세부 사항', 'toeic'),
('otherwise', 'adv . 달리 : 그렇지 않으면', 'toeic'),
('increment', 'n . ( 양적 ) 증가 임금 인상', 'toeic'),
('effective', 'ad ( 법률', 'toeic'),
('in addition', 'phr . 덧붙여', 'toeic'),
('redeem', 'v . 되찾다 . ( 상품권 등 을 ) 상품 이나 현금 으로 교환 하다', 'toeic'),
('priority', 'n . 우선 사항', 'toeic'),
('track', 'v . ( 전개 / 진행 과정 을 ) 추적 하다 n . 궤도', 'toeic'),
('retain', 'v . 보유 하다 . 유지 하다', 'toeic'),
('monitor', 'v . 주시 [ 모니터 ] 하다', 'toeic'),
('poll (poul) = survey', 'n . 여론 조사 : 투표 | v . 여론 조사 를 하다 : 득표 하다', 'toeic'),
('appreciation', 'n . 감사', 'toeic'),
('immediate', 'ad . 즉각적인', 'toeic'),
('pending', 'adj . 미결인', 'toeic'),
('utility bills', 'phr . 공과금', 'toeic'),
('conserve', 'v . 아껴 쓰다', 'toeic'),
('conservation', '보존', 'toeic'),
('conform to', 'v . 지키다 . 준수 하다', 'toeic'),
('evaluate', 'v . 평가 하다', 'toeic'),
('accommodate', 'v . 요구 등에 부용 하다 . 수용 하다 . ( 사람 을 ) 숙박 시키다', 'toeic'),
('subscribe to', 'v . 구독 하다', 'toeic'),
('fund', 'n . 자금 v . 자금 을 대다', 'toeic'),
('consist of', 'v.- 로 구성 되다', 'toeic'),
('attempt', 'n . 시도 v . 시도 하다 . 노력 하다', 'toeic'),
('similar', 'adj . 비슷한', 'toeic'),
('promote', 'v . 홍보 하다 . 승진 시키다 ; 증진 / 촉진시키다', 'toeic'),
('factor', 'n . 요소', 'toeic'),
('regarding', 'prep.- 에 관하여', 'toeic'),
('submit', 'v . 제출 하다 . 제기 하다', 'toeic'),
('compliance', 'n . ( 법 / 규칙 의 ) 준수', 'toeic'),
('probation period', 'phr . 수습 기간', 'toeic'),
('permit', 'n . 허가증 v . 허가 / 허용 하다', 'toeic'),
('a handful of', 'phr . 소수 의', 'toeic'),
('notify', 'v.- 에게 알리다 . 통지 하다', 'toeic'),
('release', 'v . 공개 하다 . 발표 하다 . 출시 하다 n . 발표', 'toeic'),
('deficit', 'n . 적자', 'toeic'),
('address', 'v . ( 문제 등 을 ) 다루다', 'toeic'),
('detailed', 'adj . 자세한', 'toeic'),
('fulfill', 'v . 이행 하다 ; 충족 시키다 . 달성 ( 성취 ] 하다', 'toeic'),
('total', 'adj . 전체 의', 'toeic'),
('estimate', 'n . 추정 ( 치 ) : 견적 ( 서 ) ( = a quote ) v . 추산 하다 . 추정 하다', 'toeic'),
('underestimate', 'v . 과소 평가 하다 n . 과소 평가', 'toeic'),
('estimation', 'n . 판단 ( 평가 ]', 'toeic'),
('estimative', 'ad 평가의', 'toeic'),
('reliable', 'ad . 믿을 만한', 'toeic'),
('thus far (=so far', 'since)', 'toeic'),
('stimulate', 'v . 자극 하다 . 격려 하다', 'toeic'),
('occasion', 'n . 행사 : 때', 'toeic'),
('occasionally', 'adv . 때때로', 'toeic'),
('occasional', 'adj', 'toeic'),
('correspondence', 'n . ( 남과 주고 받는 ) 서신 [ 편지 ] . 서신 왕래', 'toeic'),
('setback', 'n . 차질', 'toeic'),
('endeavor', 'n . 노력', 'toeic'),
('construction', 'n . 건설', 'toeic'),
('serve', 'v . ( 상품 / 서비스 를 ) 제공 하다 . 근무 하다', 'toeic'),
('treat', 'v . 대접 하다 : ( 특정한 태도 로 ) 대하다 . 처리 하다 ; 치료 하다 n . 특별한 대접', 'toeic'),
('numerous', 'adj . 매우 많은', 'toeic'),
('solely', 'adv . 오로지', 'toeic'),
('acknowledge', 'v . 인정 하다 : ~ 에게 감사 를 표하다 . 받았음 을 알리다', 'toeic'),
('setback', 'n . 차질', 'toeic'),
('endeavor', 'n . 노력', 'toeic'),
('construction', 'n . 건설', 'toeic'),
('serve', 'v . ( 상품 / 서비스 를 ) 제공 하다 . 근무 하다', 'toeic'),
('treat', 'v . 대접 하다 : ( 특정한 태도 로 ) 대하다 . 처리 하다 ; 치료 하다 n . 특별한 대접', 'toeic'),
('numerous', 'adj . 매우 많은', 'toeic'),
('solely', 'adv . 오로지', 'toeic'),
('acknowledge', 'v . 인정 하다 : ~ 에게 감사 를 표하다 . 받았음 을 알리다', 'toeic'),
('alert', 'adj . 경계 하는', 'toeic'),
('engrave', 'v . 새기다 . 조각 하다', 'toeic'),
('readership', 'n . 독자 수 ( 중 ]', 'toeic'),
('interact', 'v . 소통 하다', 'toeic'),
('boost', 'n . 증가', 'toeic'),
('at one''s earliest convenience', 'phr . 되도록 일찍', 'toeic'),
('keep up with', 'phr . ( 소식 에 대해 계속 ) 알다 . ( 뒤쳐 지지 않고 상태 를 ) 계속 유지 하다 . 뒤쳐 지지 않다', 'toeic'),
('payment', 'n . 결제', 'toeic'),
('by oneself', 'phr . 혼자서', 'toeic'),
('specifically', 'adv . 특별히', 'toeic'),
('nomination', 'n . 임명', 'toeic'),
('demonstrate', 'v . 설명 ( 증명 ) 하다 : 시연 하다', 'toeic'),
('demonstrator', 'n . 시범 자', 'toeic'),
('offset', 'v . 상쇄 하다 . 메우다 n . 차감 계산', 'toeic'),
('benefit', 'v . 혜택 ( 이득 ) 을 보다 유익 하다 n . 혜택', 'toeic'),
('Instruction', 'n . 가르침 : 지시 사항', 'toeic'),
('promotion', 'n . 승진', 'toeic'),
('earn', 'v . ( 금전 을 ) 벌다 . ( 평판 을 ) 얻다', 'toeic'),
('complaint', 'n . 불만 사항', 'toeic'),
('appliance', 'n . ( 가정용 ) 기기', 'toeic'),
('admission', 'n . 입장 : 입학', 'toeic'),
('travel expenses', 'phr . 여행 경비', 'toeic'),
('reimbursement', 'n . 환급', 'toeic'),
('misplace', 'v . 잃어 버리다 . 제자리 에 두지 않다', 'toeic'),
('editorial', 'adj . 편집 의 n . 사설', 'toeic'),
('resume', 'v . 다시 시작 하다', 'toeic'),
('potential', 'adj . 가능성 이 있는', 'toeic'),
('device', 'n . 기기', 'toeic'),
('voucher', 'n . 쿠폰', 'toeic'),
('devise', 'v . 고안 하다 . 발명 하다', 'toeic'),
('expenditure', 'n . 지출', 'toeic'),
('shortfall', 'n . 부족액', 'toeic'),
('significance', 'n . 중요성', 'toeic'),
('significant', 'adj . 상당한', 'toeic'),
('incrementally', 'adv . 점진적 으로', 'toeic'),
('resolve', 'v . 해결 하다 .', 'toeic'),
('relevant work experience', 'phr . 관련 분야 의 경력', 'toeic'),
('affiliate', 'n . 계열사 v.- 와 제휴 시키다', 'toeic'),
('be affiliated with', 'v.- 와 제휴 를 맺다 . ~ 와 관계 가 있다', 'toeic'),
('property', 'n . 재산 : 부동산', 'toeic'),
('load', 'v . ( 짐을 ) 싣다 . 적재 하다 n . 적하', 'toeic'),
('comply with', 'v . 준수 하다', 'toeic'),
('overbook', 'v . 예약 을 한도 이상 으로 받다', 'toeic'),
('malfunction', 'n . 고장 v . 오작동 하다', 'toeic'),
('dedicated', 'adj . 전념 하는', 'toeic'),
('waive', 'v . 적용 하지 않다', 'toeic'),
('coincide with', 'phr . 동시에 일어나 다', 'toeic'),
('assist', 'v . 도와 주다 n . 원조', 'toeic'),
('testimonial', 'n . 추천 글', 'toeic'),
('affordability', 'n . 저렴한 비용', 'toeic'),
('equivalent', 'adj . 해당 하는', 'toeic'),
('deliberate', 'adj . 고의적 인 : 신중한 v . 심사숙고 하다', 'toeic'),
('prominent', 'adj . 중요한', 'toeic'),
('punctual', 'ad', 'toeic'),
('rigorous', 'adj . 철저한', 'toeic'),
('selective', 'adj . 까다로운', 'toeic'),
('punctual', 'ad', 'toeic'),
('rigorous', 'adj . 철저한', 'toeic'),
('selective', 'adj . 까다로운', 'toeic'),
('challenging', 'adj . 어려운', 'toeic'),
('restoration', 'n . ( 낡은 건물 · 그림 의 ) 복원', 'toeic'),
('officially', 'adv . 공식적 으로', 'toeic'),
('officially', 'adv . 공식적 으로', 'toeic'),
('slightly', 'adv . 약간', 'toeic'),
('substantially', 'adv . 상당히', 'toeic'),
('nearly', 'adv . 거의', 'toeic'),
('immediately', 'adv . 즉시', 'toeic'),
('enrollment', 'n . 등록', 'toeic'),
('requirement', 'n . 필요 조건', 'toeic'),
('recommend', 'v . 추천 하다', 'toeic'),
('carefully', 'adv . 조심 스럽게', 'toeic'),
('enough', 'adj. 충분한 adv . 충분히', 'toeic'),
('transport', 'v . 수송 하다 . 운송 하다 n . 수송', 'toeic'),
('exceptional', 'adj . 예외적 인 : ( 이례적 일 정도로 ) 뛰어난', 'toeic'),
('proof', 'n . 증명 ( 서 )', 'toeic'),
('prospective', 'adj . 장래 의', 'toeic'),
('update', 'n . 업데이트', 'toeic'),
('suitable', 'adj . 적합한', 'toeic'),
('seek', 'v . 찾다 . 구하다', 'toeic'),
('receive', 'v . 받다', 'toeic'),
('demand', 'n . 수요 . 요구 v . 요구 하다', 'toeic'),
('accustomed', 'adj.- 에 익숙한', 'toeic'),
('aspire', 'v . 열망 하다', 'toeic'),
('accompany', 'v . 동행 하다 : 동반 하다', 'toeic'),
('schedule', 'v . 일정을 잡다 n . 일정', 'toeic'),
('actively', 'adv . 적극적으로', 'toeic'),
('extensive', 'adj . 광범위한', 'toeic'),
('statement', 'n . 성명 ( 서 ) : 명세서', 'toeic'),
('solicitation', 'n . 간청', 'toeic'),
('be credited with', 'phr . ~ 로 인정 받다 . 신뢰 를 얻다', 'toeic'),
('opposite', 'adj . 맞은 편의 반대 의 prep. 20 (across from)', 'toeic'),
('accessible', 'adj . 접근 가능한', 'toeic'),
('assure', 'v . 장담 하다', 'toeic'),
('vacant', 'ad . 공석의', 'toeic'),
('given', 'prep.- 를 고려 해볼 때', 'toeic'),
('specify', 'v . 구체적으로 명시하다', 'toeic'),
('conflict', 'n . 갈등', 'toeic'),
('influx', 'n . 유입', 'toeic'),
('nonrefundable', 'adj . 환불 되지 않는', 'toeic'),
('subsequent', 'adj . 차후의', 'toeic'),
('interfere with', 'v . 방해 하다 ; 간섭 하다', 'toeic'),
('flyer', 'n . 전단지', 'toeic'),
('party', 'n . 단체 : 정당', 'toeic'),
('stress', 'v . 강조 하다 n . 강조', 'toeic'),
('advancement', 'n . 진보 : 승진', 'toeic'),
('wealth', 'n . 재산', 'toeic'),
('noticeable', 'adj . 눈 에 띄는', 'toeic'),
('withdraw', 'v . 빼내다 . 인출 하다 . 철수 시키다', 'toeic'),
('withdraw', 'v . 빼내다 . 인출 하다 . 철수 시키다', 'toeic'),
('lead', 'v . 이끌다 . 안내 하다 : 이어 지다 . 초래 하다 ( in )', 'toeic'),
('now that', 'conj.- 이기 때문에', 'toeic'),
('entry', 'n . ( 경기 등 의 ) 참가자 : 출품물', 'toeic'),
('pay off', 'phr . 성과 를 올리다 . 성공 하다', 'toeic'),
('surplus', 'n . 잉여 ( 물 )', 'toeic'),
('funding', 'n . 자금 : 자금 제공 [ 재정 지원 ]', 'toeic'),
('operate', 'v . 운영 하다 : 작동 하다', 'toeic'),
('grant', 'n . ( 정부 ) 보조금 v . 주다 . 수여 하다', 'toeic'),
('relief', 'n . 안도', 'toeic'),
('duplicate', 'v . 복사 하다 . 복제 하다 n . 사본', 'toeic'),
('referral', 'n . 소개', 'toeic'),
('worsen', 'v . 악화 되다 : 악화 시키다', 'toeic'),
('fully', 'adv . 완전히', 'toeic'),
('locate', 'v . 위치 시키다 : ( - 의 정확한 위치를 ) 찾아 내다', 'toeic'),
('representative', 'n . 직원', 'toeic'),
('gathering', 'n . 모임', 'toeic'),
('throughout', 'prep . 내내', 'toeic'),
('negotiate', 'v . 협상 하다', 'toeic'),
('markedly', 'adv . 현저 하게', 'toeic'),
('purpose', 'n . 목적', 'toeic'),
('in light of', 'prep.- 에 비추어', 'toeic'),
('expertise', 'n . 전문 지식 [ 기술 ] . 불가 산 명사', 'toeic'),
('expert', 'n . 전문가', 'toeic'),
('entry', 'n . ( 경기 등 의 ) 참가자 : 출품물', 'toeic'),
('pay off', 'phr . 성과 를 올리다 . 성공 하다', 'toeic'),
('surplus', 'n . 잉여 ( 물 )', 'toeic'),
('funding', 'n . 자금 : 자금 제공 [ 재정 지원 ]', 'toeic'),
('submission', 'n . ( 서류 / 제안서 등 의 ) 제출', 'toeic'),
('operate', 'v . 운영 하다 : 작동 하다', 'toeic'),
('grant', 'n . ( 정부 ) 보조금 v . 주다 . 수여 하다', 'toeic'),
('relief', 'n . 안도', 'toeic'),
('duplicate', 'v . 복사 하다 . 복제 하다 n . 사본', 'toeic'),
('referral', 'n . 소개', 'toeic'),
('worsen', 'v . 악화 되다 : 악화 시키다', 'toeic'),
('glowing', 'adj . 빛나는 : 극찬 하는', 'toeic'),
('obligation', 'n . 의무', 'toeic'),
('Instructional', 'adj . 교육용의', 'toeic'),
('administer', 'v . 운영 하다 . 관리 하다 실시 하다 . 집행 하다', 'toeic'),
('run', 'v . 진행 [ 계속 ] 되다 . 제공 되다 ; 운영 하다 ( 기계 ) 돌아가다', 'toeic'),
('significant', 'adj . 중요한', 'toeic'),
('ample', 'adj . 많은', 'toeic'),
('commission', 'n . 수수료', 'toeic'),
('follow up on', 'phr . ~ 에 대해 후속 조치 하다 ; ~ 을 계속 주구 / 이행 하다', 'toeic'),
('proceed', 'v . 계속 해서 ~ 하다 . 진행 되다 . 나아가다', 'toeic'),
('proceedings', 'n . 회의록', 'toeic'),
('demonstration', 'n . 시범 설명', 'toeic'),
('rate', 'n . 요금 : 속도 : 비율 v . 평가 하다', 'toeic'),
('exactly', 'adv . 정확하게', 'toeic'),
('fairly', 'adj 꽤', 'toeic'),
('restrict', 'v . 제한 하다 . 한정 하다', 'toeic'),
('recently', 'adv . 최근에', 'toeic'),
('accurate', 'adj . 정확한', 'toeic'),
('volume', 'n . 양', 'toeic'),
('compatible', 'adj . 호환 이 되는', 'toeic'),
('compatibilty', 'n . 호환성', 'toeic'),
('compatible with-', '- 와 호환 이 되는', 'toeic'),
('chief', 'adj . 주된', 'toeic'),
('forum', 'n . 포럼', 'toeic'),
('thrilling', 'adj . 스릴 있는', 'toeic'),
('attentively', 'adv . 주의 깊게', 'toeic'),
('satisfaction', 'n . 만족', 'toeic'),
('basis', 'n . 기준', 'toeic'),
('applicable', 'adj . 해당 되는', 'toeic'),
('pertaining to', 'prep.- 에 관련된', 'toeic'),
('variety', 'n . 다양 함', 'toeic'),
('incur', 'v . ( 비용 을 ) 발생 시키다 . 초래 하다', 'toeic'),
('groundbreaking', 'adj . 획기적인 n . 착공', 'toeic'),
('intend', 'v . 의도 하다 . ~ 하려고 생각 하다', 'toeic'),
('incurrence', 'n . ( 손해 를 ) 입음', 'toeic'),
('apply for', 'phr . 지원 하다', 'toeic'),
('local', 'ad . 지역 의', 'toeic'),
('apply for', '지원 하다', 'toeic'),
('apply to', '적용 하다', 'toeic'),
('quarterly', 'adj . 분기 별 의', 'toeic'),
('figure', 'n . 수치 : 인물', 'toeic'),
('encounter', 'v . ( 난관 에 ) 부딪 히다 . 우연히 마 주 치다', 'toeic'),
('volunteer', 'n . 자원 봉사자 v . 자진 하다 . 자원 봉사 하다', 'toeic'),
('obtain', 'v . 얻다', 'toeic'),
('respective', 'adj . 각각의', 'toeic'),
('equip', 'v . ( 장비 를 ) 갖추어 주다', 'toeic'),
('enthusiasm', 'n . 열광', 'toeic'),
('installation', 'n . 설치', 'toeic'),
('correspond to', 'phr.- 와 일치 하다', 'toeic'),
('available', 'adj . ( 사람이 ) 시간 이 있는', 'toeic'),
('separately', 'adv . 따로 따로', 'toeic'),
('charge', 'n . ( 상품 / 서비스 에 대한 ) 요금 : 책임 의무 : 충전 v . ( 요금 을 ) 청구 하다 . 맡기다 . 충전 하다', 'toeic'),
('traditionally', 'adv . 전통적 으로', 'toeic'),
('proximity', 'n . 가까움', 'toeic'),
('stretch', 'n . ( 길게 뻗은 ) 구간', 'toeic'),
('term', 'n . 조건 : 기간 : 용어', 'toeic'),
('emphasize', 'v . 강조 하다', 'toeic'),
('cooperation', 'n . 협력', 'toeic'),
('periodically', 'adv . 정기적 으로', 'toeic'),
('acclaimed', 'adj 칭찬 [ 호평 ] 을 받고 있는', 'toeic'),
('challenge', 'n . 도전', 'toeic'),
('rather', 'adv . 꽤', 'toeic'),
('confirm', 'v . 확인 하다 . 확정 하다', 'toeic'),
('influence', 'v . 영향 을 주다 n . 영향 ( 력 )', 'toeic'),
('prompt', 'v . ( 어떤 일 이 일어나 도록 ) 하다 . 촉발 하다 . 유도 하다 adj . 즉각적인 : 신속한', 'toeic'),
('draw', 'v . 끌다 . 끌어 들이다 . 이용 하다 . 의지 하다', 'toeic'),
('reverse', 'v . 뒤집다', 'toeic'),
('stipulate', 'v . 규정 하다 . 명기 하다', 'toeic'),
('widen', 'v . 확장 하다 . 넓히다', 'toeic'),
('categorize', 'v . 분류 하다', 'toeic'),
('marked', 'adj . 뚜렷한', 'toeic'),
('category', 'n . 범주', 'toeic'),
('consider', 'v . 고려 하다 . 숙고 하다', 'toeic'),
('impression', 'n . 인상', 'toeic'),
('inspection', 'n . 점검', 'toeic'),
('discontinue', 'v . 생산을 중단하다', 'toeic'),
('resolution', 'n . 해결', 'toeic'),
('assessment', 'n . 평가', 'toeic'),
('assess', 'v.- 을 평가 하다', 'toeic'),
('resolution', 'n . 해결', 'toeic'),
('assessment', 'n . 평가', 'toeic'),
('resolve', 'v . ( 문제 등 을 ) 해결 하다', 'toeic'),
('closely', 'adv . 면밀 하게', 'toeic'),
('extend', 'v . 연장 하다', 'toeic'),
('consult', 'v . 상의 하다', 'toeic'),
('portable', 'adj . 휴대가 쉬운', 'toeic'),
('coordinate', 'v . 조정 하다', 'toeic'),
('a series of', 'phr . 일련 의', 'toeic'),
('arguably', 'adv . ( 최상급 앞에서 ) 거의 틀림 없이', 'toeic'),
('capacity', 'n . 정원', 'toeic'),
('urgent', 'adj . 긴급한', 'toeic'),
('urgency', 'n. 긴급함', 'toeic'),
('modification', 'n . 변경', 'toeic'),
('authentic', 'adj . 진짜인', 'toeic'),
('cooperatively', 'adv . 협력 하여', 'toeic'),
('accumulate', 'v . 축적 하다 ; ( 이자', 'toeic'),
('precise', 'adj . 정확한', 'toeic'),
('steady', 'adj 끊임 없는', 'toeic'),
('overdue', 'adj . 기한이 지난', 'toeic'),
('clarify', 'v . 명확 하게 하다', 'toeic'),
('notable', 'adj . 유명한', 'toeic'),
('rental', 'n . 임대', 'toeic'),
('expire', 'vi . 만료 되다 . 끝나다', 'toeic'),
('clarification', 'n . 설명', 'toeic'),
('rely (on=upon)', 'v . ~ 에 의존 / 의지 하다', 'toeic'),
('initiate', 'v . 개시 [ 시작 ] 하다 . 착수 하다', 'toeic'),
('respected', 'adj . 홀륭한', 'toeic'),
('respected', 'adj . 홀륭한', 'toeic'),
('highly', 'adv . 매우', 'toeic'),
('respond', 'v . ( ~ 에 ) 반응 / 응답 하다', 'toeic'),
('invent', 'v . 발명하다 . 고안하다', 'toeic'),
('expense', 'n . 비용', 'toeic'),
('sizable', 'adj . 상당한 ( 크기 의 )', 'toeic'),
('cater', 'v . ( 사업 으로 행사 에 ) 음식 을 공급 [ 조달 ] 하다', 'toeic'),
('policy', 'n . 정책', 'toeic'),
('soon', 'adv . 곧', 'toeic'),
('share', 'v . 공유 하다 . 나누다 n . 몫', 'toeic'),
('instead', 'adv . 그 대신', 'toeic'),
('instead of', '~대신에', 'toeic'),
('appropriate', 'adj . 적절한', 'toeic'),
('exceed', 'v . 초과하다 . 넘어서다', 'toeic'),
('particular', 'adj . 특정한', 'toeic'),
('range', 'n . 다양성', 'toeic'),
('perishable', 'adv . 신속히', 'toeic'),
('differentiate', 'v . 구분 짓다 . 구별 하다', 'toeic'),
('length', 'n . 길이 : 기간', 'toeic'),
('compensation', 'n . 보상 ( 금 )', 'toeic'),
('receipt', 'n . 영수증 ( 가산 명사 ) : 수령 ( 불가 산 명사 )', 'toeic'),
('deteriorate', 'v . 악화 되다 . 더 나 빠지다', 'toeic'),
('position', 'n . 일자리', 'toeic'),
('comparable', 'adj . 비슷한', 'toeic'),
('compare', 'v . 비교 하다 . 견주다', 'toeic'),
('comparison', 'n . 비교 비유', 'toeic'),
('diversionn', '. 전환', 'toeic'),
('divert', 'v . 방향을 바꾸게 하다', 'toeic'),
('secure', 'v . 안전하게 지키다 : 얻다 . 확보 하 다 . 고정 시키다 adj . 안전한', 'toeic'),
('advocate', 'n . 지지자', 'toeic'),
('contemporary', 'adj . 현대의', 'toeic'),
('customary', 'adj . 관례 적인', 'toeic'),
('customarily', 'adv . 관례 ( 습관 ] 적 으로', 'toeic'),
('customs', 'n', 'toeic'),
('spare', 'adj . 여분의', 'toeic'),
('confidential', 'ad . 기밀의', 'toeic'),
('confidentiality', 'n . 비밀', 'toeic'),
('exceptionally', 'adv . 예외적 으로', 'toeic'),
('analysis', 'n . 분석', 'toeic'),
('generate', 'v . 발생 시키다', 'toeic'),
('within', 'prep.- 이내에', 'toeic'),
('dependent', 'adj . ~ 에 의존 하는 ( on )', 'toeic'),
('financially', 'adv . 재정적 으로', 'toeic'),
('deliberation', 'n . 심사숙고 : 토의', 'toeic'),
('expand', 'v . 확장 하다 . 확대 하다 . 늘리다', 'toeic'),
('likely', 'adj.- 할 것 같은', 'toeic'),
('allow', 'v . 허락 하다 . 허용 하다', 'toeic'),
('plentiful', 'adj . 풍부한', 'toeic'),
('establish', 'v . 설립 하다 . 세우다 확고히 하다', 'toeic'),
('relevant', 'adj . 관련 있는', 'toeic'),
('pick up', 'phr . 집어 들다 . 찾아 가다 : [ 사람 을 ] 태우 러 가다 . : 좋아 지다', 'toeic'),
('abundant', 'adj . 풍부한', 'toeic'),
('seldom', 'adv . 좀처럼 [ 거의 ] ~ 않는', 'toeic'),
('inventive', 'adj . 창의적인', 'toeic'),
('in case', 'con . ~ 인 경우를 대비해서 : 만약 ~ 인 경우에', 'toeic'),
('term', 'n . 조건 : 임기', 'toeic'),
('inexpensive', 'adj . 비싸지 않은', 'toeic'),
('amount', 'n . 양', 'toeic'),
('typically', 'adv . 보통', 'toeic'),
('finalize', 'v . 마무리 짓다', 'toeic'),
('adjustment', 'n . ( 약간 의 ) 수정', 'toeic'),
('based', 'adj . ( ~ 에 ) 기반을 둔 : 본사를 둔', 'toeic'),
('certify', 'v . ( 특히 서면 으로 ) 증명 하다 . 자 격증 을 교부 하다', 'toeic'),
('vast', 'adj . 어마 어마한', 'toeic'),
('marginally', 'adv . 아주 조금', 'toeic'),
('drastically', 'adv . 대폭 으로', 'toeic'),
('maximum', 'ad . 최대의', 'toeic'),
('regretfully', 'adv . 유감 스럽게도', 'toeic'),
('incomplete', 'adj . 미완성의', 'toeic'),
('enormously', 'adv . 엄청나게', 'toeic'),
('upcoming', 'adj . 다가오는', 'toeic'),
('admirable', 'adj . 감탄 할만한', 'toeic'),
('experience', 'n . 경험 v . 경험 하다 . 겪다', 'toeic'),
('additional', 'adj . 주가 의', 'toeic'),
('ethical', 'adj . 윤리적인', 'toeic'),
('absolute', 'adj . 절대적인', 'toeic'),
('humidity', 'n . 습도', 'toeic'),
('humidity', 'n . 습도', 'toeic'),
('lucrative', 'adj . 수익성이 있는', 'toeic'),
('stable', 'adj . 안정된', 'toeic'),
('disruption', 'n . 중단', 'toeic'),
('disruption', 'n . 중단', 'toeic'),
('replace', 'v . 대체하다 . 교체하다', 'toeic'),
('brief', 'adj . 간략한', 'toeic'),
('indeed', 'adv . 확실히', 'toeic'),
('plenty', 'n . 풍부한 양', 'toeic'),
('incredible', 'adj . 엄청난', 'toeic'),
('attached', 'adj . 첨부된', 'toeic'),
('handle', 'v . 다루다 . 처리하다', 'toeic'),
('celebratory', 'adj . 축하 하는', 'toeic'),
('recognition', 'n . 인정', 'toeic'),
('publication', 'n . 간행물', 'toeic'),
('reflect', 'v . 반영 하다', 'toeic'),
('reflectionn', 'n. 반영 : 심사숙고', 'toeic'),
('previously', 'adv . 이전에', 'toeic'),
('inspect', 'v . 점검 하다', 'toeic'),
('notice', 'n . 공지', 'toeic'),
('until further notice', '추후 공지 가 있을 때 까지', 'toeic'),
('initial', 'adj . 처음 의', 'toeic'),
('competitor', 'n . 경쟁 업체', 'toeic'),
('compete with 사람 for 목적', 'vi . 경쟁 하다', 'toeic'),
('host', 'v . 개최 하다 . 주최 하다 n . ( 손님 을 초대 한 ) 주인 : ( TV . 라디오 프로 의 ) 진행자', 'toeic'),
('atmosphere', 'n . 분위기', 'toeic'),
('directly', 'adv . 곧바로 [ 즉시 )', 'toeic'),
('submission', 'n . ( 서류 · 제안서 등 의 ) 제출 ( 물 )', 'toeic'),
('specialize', 'v . 전문 으로 하다', 'toeic'),
('disappointing', 'adj . 실망 스러운', 'toeic'),
('availability', 'n . 유효성', 'toeic'),
('largely', 'adv . 주로', 'toeic'),
('refer', 'v . 보내다 . 소개 하다 언급 하다 . 참고 하다', 'toeic'),
('refer to 명사', '언급 하다 . ~ 을 참고 하다', 'toeic'),
('refer A to B', 'A 를 B 에 소개 하다', 'toeic'),
('adequate', 'adj . 충분한 : 적절한', 'toeic'),
('appointment', 'n . ( 공적 ) 약속', 'toeic'),
('concerning', 'prep.- 에 관한', 'toeic'),
('launch', 'n . 개시', 'toeic'),
('waterfront', 'n . ( 도시 의 ) 해안가 물가', 'toeic'),
('approximately', 'adv . 약', 'toeic'),
('affordable', 'adj . ( 가격 등 이 ) 알맞은', 'toeic'),
('auditor', 'n . 회계 감사관', 'toeic'),
('maintenance', 'n . 유지 : ( 보수 ) 관리', 'toeic'),
('contribution', 'n . 기여', 'toeic'),
('in light of', 'prep.- 에 비추어', 'toeic'),
('depend', 'v . 의존 하다 : ~ 에 달려 있다', 'toeic'),
('be contingent on', '~ 에 달려 있다', 'toeic'),
('overhaul', 'v . 점검 하다 n . 점검', 'toeic'),
('persuade', 'v . 설득 하다', 'toeic'),
('conduct', 'v . ( 업무 따위 를 ) 실시 하다', 'toeic'),
('dramatic', 'adj . 극적인', 'toeic'),
('method', 'n . 방법', 'toeic'),
('contain', 'v.- 이 들어 있다 . 포함 하다', 'toeic'),
('devoted', 'adj . 현신 적인', 'toeic'),
('container', 'n . 용기 : ( 화물 ) 컨테이너', 'toeic'),
('immediately', 'adv . 즉시', 'toeic'),
('accumulation', 'n . 축적', 'toeic'),
('capability', 'n . 능력', 'toeic'),
('casually', 'adv . 이따금', 'toeic'),
('component', 'n . 부품', 'toeic'),
('coverage', 'n . ( 적용 ) 범위', 'toeic'),
('relinquish', 'v . ( 권리 등 을 ) 포기 [ 양도 ] 하다', 'toeic'),
('relinquish one''s right', '권리를 포기하다', 'toeic'),
('evenly', 'adv . 고르게', 'toeic'),
('efficiently', 'adv . 능률적 으로', 'toeic'),
('expose', 'v . 드러내다 . 노출 시키다', 'toeic'),
('client', 'n . 고객', 'toeic'),
('function', 'n . 기능 ; 역할 v . 기능 하다 . 작동 하다', 'toeic'),
('insulation', 'n . 절연체 : 단열', 'toeic'),
('hypothesis', 'n . 가설', 'toeic'),
('complete', 'v . 완료 하다 . 끝 마치다 adj . 완벽한 완전한', 'toeic'),
('hypothetical', 'adj . 가정 의', 'toeic'),
('hypothesize', 'v . 가정 하다', 'toeic'),
('supervisor', 'n . 상사', 'toeic'),
('supervisor', 'n . 상사', 'toeic'),
('diverse', 'adj . 다양한', 'toeic'),
('arrangement', 'n . 준비', 'toeic'),
('directory', 'n . ( 이름 · 주소 등 의 ) 안내 책자 : ( 빌딩 의 ) 입주자 안내판', 'toeic'),
('state', 'v . 말하다 . 진술 하다 : ( 문서 에 ) 명시 하다', 'toeic'),
('district', 'n . 지구 ( 지역 )', 'toeic'),
('solidify', 'v . 굳히다 . 확고히 하다', 'toeic'),
('assistant', 'n . 조력자', 'toeic'),
('ideal', 'adj . 이상적인', 'toeic'),
('be ideal for', '에 이상적 이다', 'toeic'),
('be ideal for- 에 required', 'adj. 필수의', 'toeic'),
('qualify', 'v.- 에게 자격 을 주다 . 적임 으로 하다', 'toeic'),
('advance', 'v . 승진 하다 . 출세 하다 n . 진보', 'toeic'),
('motivate', 'v . 동기 를 부여 하다', 'toeic'),
('profit', 'n. 수익 이익', 'toeic'),
('statistics', 'n 통계 ( 학 )', 'toeic'),
('eliminate', 'v . 없애다 . 제거 하다', 'toeic'),
('cover', 'v . ( 비용 따위 를 ) 충당 하다 . 대다 ; 다루다 . 포함 하다 : ( 보험 으로 ) 보장 하다', 'toeic'),
('cover expenses', '비용 을 대다 . 충당 하다', 'toeic'),
('flexible', 'adj . 융통성 이 있는', 'toeic'),
('renovate', 'v . 개조 하다 . 보수 하다', 'toeic'),
('reimbursement', 'v . 변상', 'toeic'),
('in advance', 'phr . 미리', 'toeic'),
('adjustable', 'adj . 조절 가능한', 'toeic'),
('inquiry', 'n . 문의 : 조사', 'toeic'),
('manufacture', 'v . 제조 하다 . 생산 하다 n . 제조', 'toeic'),
('inquire', '1V . 질문 하다', 'toeic'),
('banquet', 'n . ( 공식 ) 연회', 'toeic'),
('refreshing', 'adj . 신선한', 'toeic'),
('commute', 'v . 통근 하다 . 통학 하다 n 통근 ( 거리 )', 'toeic'),
('remind', 'v . 상기 시키다 . 생각 나게 하다', 'toeic'),
('registration', 'n . 등록', 'toeic'),
('leading', 'adj . 주요한', 'toeic'),
('nominate', 'v . ( 후보자 로 ) 추천 하다 . 임명 하다 . 지정 하다', 'toeic'),
('cancellation', 'n . 취소', 'toeic'),
('distribute', 'v . 유통 시키다', 'toeic'),
('invoice', 'n . 송장', 'toeic'),
('look forward to', 'phr.- 을 고대 하다 . 기다리다', 'toeic'),
('specification', 'n . 설명서', 'toeic'),
('take effect', 'phr . 발효 하다 . 효력을 나타내다', 'toeic'),
('fluctuation', 'n . 변동', 'toeic'),
('merger', 'n . ( 회사 의 ) 합병', 'toeic'),
('mutually', 'adv . 서로', 'toeic'),
('mutual', 'ad . 상호간의', 'toeic'),
('mutuality', 'n . 상호 관계', 'toeic'),
('errand', 'n . 심부름', 'toeic'),
('imperative', 'adj . 반드시 해야 하는', 'toeic'),
('maximize', 'v . 극대화 하다 . 최대한 활용 하다', 'toeic'),
('mind', 'v . 꺼리다 . 싫어 하다', 'toeic'),
('individual', 'n . 개인', 'toeic'),
('determine', 'v . 결정 하다', 'toeic'),
('instructor', 'n . 강사', 'toeic'),
('instruct', 'v . 가르치다 ; 지시 하다', 'toeic'),
('instruction', 'n . 교육', 'toeic'),
('complimentary', 'adj . 무료의', 'toeic'),
('employment', 'n . 취업', 'toeic'),
('confidence', 'n . 신뢰', 'toeic'),
('advantage', 'n . 장점', 'toeic'),
('rise', 'n . 증가', 'toeic'),
('awareness', 'n . ( - 의 중요성 에 대한 ) 의식', 'toeic'),
('since', 'prep.- 이래로 conj.- 이래로 : - 때문에 adv . 그 ( 때 ) 이후 로', 'toeic'),
('transfer', 'v . 옮기다', 'toeic'),
('stand', 'v . 서다 . 서 있다 n . ( 공개적 으로 드러내는 ) 태도 [ 의견 ] : 가판대', 'toeic'),
('stance', 'n . 입장', 'toeic'),
('awareness', 'n . ( - 의 중요성 에 대한 ) 의식', 'toeic'),
('since', 'prep.- 이래로 conj.- 이래로 : - 때문에 adv . 그 ( 때 ) 이후 로', 'toeic'),
('transfer', 'v . 옮기다', 'toeic'),
('stand', 'v . 서다 . 서 있다 n . ( 공개적 으로 드러내는 ) 태도 [ 의견 ] : 가판대', 'toeic'),
('support', 'n . 지지', 'toeic'),
('retire', 'v . 은퇴 하다 . 퇴직 하다', 'toeic'),
('resourceful', 'adj . 기지 가 있는', 'toeic'),
('predecessor', 'n . 전임자', 'toeic'),
('praise', 'v . 칭찬 하다 n . 칭찬', 'toeic'),
('particularly', 'adv . 특히', 'toeic'),
('limited', 'ad', 'toeic'),
('hire', 'v . 고용 하다 n . 신입 직원', 'toeic'),
('field', 'n . 분야', 'toeic'),
('dependable', 'adj . 믿을 수 있는', 'toeic'),
('duty', 'n . 직무', 'toeic'),
('commensurate', 'adj . ( 자질 등에 ) 상응 하는 . 비례 하는', 'toeic'),
('appraisal', 'n . 평가', 'toeic'),
('skill', 'n . 기술', 'toeic'),
('renew', 'v . 연장 하다', 'toeic'),
('productivity', 'n . 생산성', 'toeic'),
('recruit', 'n . 신입 사원', 'toeic'),
('recommendation', 'n . 추천 ( 서 )', 'toeic'),
('recruitment', 'n . 신규 모집', 'toeic'),
('recruiter', 'n . 모집 자', 'toeic'),
('listing', 'n . ( 공식적인 ) 목록', 'toeic'),
('evident', 'adj . 분명한', 'toeic'),
('timely', 'ad ) 시기 적절한', 'toeic'),
('evidence', 'n . 증거', 'toeic'),
('evidently', 'adv . 분명히', 'toeic'),
('consideration', 'n . 고려 ( 사항 )', 'toeic'),
('consistently', 'adv . 항상', 'toeic'),
('clerical', 'adj . 사무직의', 'toeic'),
('accomplished', 'adj . ( 기량 이 ) 뛰어난', 'toeic'),
('applicant', 'n . 지원자', 'toeic'),
('operation', 'n . 사업', 'toeic'),
('Insurance', 'n . 보험 : 보험금', 'toeic'),
('distraction', 'n . 주의 산만 기분 전환', 'toeic'),
('listing', 'n . ( 공식적인 ) 목록', 'toeic'),
('evident', 'adj . 분명한', 'toeic'),
('consideration', 'n . 고려 ( 사항 )', 'toeic'),
('consistently', 'adv . 항상', 'toeic'),
('clerical', 'adj . 사무직 의', 'toeic'),
('accomplished', 'adj . ( 기량 이 ) 뛰어난', 'toeic'),
('applicant', 'n . 지원자', 'toeic'),
('operation', 'n . 사업', 'toeic'),
('Insurance', 'n . 보험 : 보험금', 'toeic'),
('distraction', 'n . 주의 산만 기분 전환', 'toeic'),
('statistics', 'n . 통계 ( 학 )', 'toeic'),
('eliminate', 'v . 없애다 . 제거 하다', 'toeic'),
('cover', 'v . ( 비용 따위 를 ) 충당 하다 . 대다 ; 다루다 . 포함 하다 : ( 보험 으로 ) 보장 하다', 'toeic'),
('flexible', 'adj . 융통성 이 있는', 'toeic'),
('statistical', 'adj . 통계 ( 상 ) 의', 'toeic'),
('statistically', 'adv . 통계적 으로', 'toeic'),
('renovate', 'v . 개조 하다 . 보수 하다', 'toeic'),
('reimburse', 'n . 변제 하다', 'toeic'),
('in advance', 'phr . 미리', 'toeic'),
('inquiry', 'n . 문의 : 조사', 'toeic'),
('manufacture', 'v . 제조 하다 . 생산 하다 n . 제조', 'toeic'),
('contagious', 'adj . 전염성 의 : 퍼지기 쉬운', 'toeic'),
('protective', 'adj . 보호 하는', 'toeic'),
('predict', 'v . 예측 하다 . 예견 하다', 'toeic'),
('deliver', 'v . 배달 하다 . 배송 하다 : ( 연설 을 ) 하다', 'toeic'),
('introduce', 'v . 소개 하다 ; 도입 하다 . ( 상품 을 ) 선보이다', 'toeic'),
('shipment', 'n . 수송', 'toeic'),
('concern', 'n . 우려', 'toeic'),
('process', 'v . 처리 하다 : 가공 하다 n . 과정', 'toeic'),
('involve', 'v . 수반 ( 포함 ] 하다 . 연루 [ 참여 ] 시키다', 'toeic'),
('attract', 'v . ( 사람 / 관심 ) 끌다 . 끌어 모으다', 'toeic'),
('appear', 'v.- 인 것 같다 . 나타나다 나오다', 'toeic'),
('appearance', 'n . ( 걸 ) 모습', 'toeic'),
('Itinerary', 'n . 여행 일정 ( 표 )', 'toeic'),
('subscribe', 'v . ( 신문 · 잡지 등 을 ) 구독 하다', 'toeic'),
('chemical', 'adj . 화학 의', 'toeic'),
('decline', 'n . 감소', 'toeic'),
('preparation', 'n . 준비', 'toeic'),
('film', 'n . 영화 v . 촬영 하다 . 영화화 하다', 'toeic'),
('reduce', 'v . 줄이다', 'toeic'),
('security', 'n . 보안', 'toeic'),
('shift', 'n . 교대조', 'toeic'),
('deadline', 'n . 기한', 'toeic'),
('document', 'n . 서류', 'toeic'),
('attentive', 'adj', 'toeic'),
('payable', 'adj . 지불 해야 하는', 'toeic'),
('extension', 'n . ( 기한 ) 연장 : 내선 ( 번호 )', 'toeic'),
('manual', 'n . 설명서', 'toeic'),
('resolve', 'v . 해결 하다 . 풀다', 'toeic'),
('assignment', 'n . 임무 [ 업무 ]', 'toeic'),
('contractor', 'n . 계약자', 'toeic'),
('performance', 'n . 수행', 'toeic'),
('commercial', 'n . ( TV- 라디오 ) 광고 adj . 상업 의', 'toeic'),
('resident', 'n . 거주자', 'toeic'),
('annually', 'adv . 매년', 'toeic'),
('anticipate', 'v . 예상 하다 . 예측 하다', 'toeic'),
('financial', 'adj . 재정 의', 'toeic'),
('raise', 'vt 올리다 . 인상 하다 n . ( 임금 ) 인상', 'toeic'),
('revenue', 'n . 수익', 'toeic'),
('significant', 'ad . 상당한 중요한', 'toeic'),
('nutrition', 'n . 영양물', 'toeic'),
('established', 'adj', 'toeic'),
('relocate', 'v . 이동 하다 . 이전 하다', 'toeic'),
('article', 'n . ( 신문 / 잡지 ) 등 의 글', 'toeic'),
('ongoing', 'adj . ( 계속 ) 진행 중인', 'toeic'),
('donate', 'v . 기부 하다', 'toeic'),
('corporate', 'adj . 법인 ( 체 ) 의', 'toeic'),
('for free', 'phr . 공짜 로', 'toeic'),
('purchase', 'n . 구입 ( 한 것 ) v . 구입 하다 . 사다', 'toeic'),
('reschedule', 'v . 일정 을 변경 하다', 'toeic'),
('valid', 'adj . 유효한', 'toeic'),
('commitment', 'n . 전념', 'toeic'),
('temporarily', 'adv . 일시적 으로', 'toeic'),
('trial', 'n . 무료 체험 : 시험', 'toeic'),
('contribute', 'v . 기여 하다 . 기부 하다 : 기고 하다', 'toeic'),
('contribute', 'v . 기여 하다 . 기부 하다 : 기고 하다', 'toeic'),
('entire', 'adj . 전체 의', 'toeic'),
('revise', 'v . 수정 하다 . 변경 하다', 'toeic'),
('historic', 'adj . 역사적인', 'toeic'),
('passenger', 'n . 승객', 'toeic'),
('executive', 'n . 간부', 'toeic'),
('sponsor', 'n . 후원자 스폰서 v . 후원 하다', 'toeic'),
('close', 'adj . 가까운', 'toeic'),
('construction', 'n . 건설', 'toeic'),
('entrance', 'n . 입구 : 문 들어가기', 'toeic'),
('entrance', 'n . 입구 : 문 들어가기', 'toeic'),
('facility', 'n . 시설', 'toeic'),
('occupy', 'v . 차지 하다', 'toeic'),
('biologist', 'n . 생물 학자', 'toeic'),
('renovation', 'n . 보수 공사', 'toeic'),
('renovator', 'n . 혁신자', 'toeic'),
('rent', 'v . ( 집을 ) 빌리다 . 임대 [ 임차 ] 하다 n . 집세', 'toeic'),
('dispose', 'v . 처리 하다 . 처분 하다 ( of )', 'toeic'),
('tenant', 'n . 세입자 : 거주자 v . ( 토지 / 가옥 등 을 ) 빌려 쓰다', 'toeic'),
('leadership', 'n . 지도력', 'toeic'),
('develop', 'v . ( 필름 을 ) 현상 하다 : 발전 시키다', 'toeic'),
('improve', 'v . 개선 하다 . 향상 시키다', 'toeic'),
('assembly', 'n . ( 기계 의 ) 조립', 'toeic'),
('instruction', 'n . 가르침 : 지시', 'toeic'),
('register', 'v . 등록 하다 : 기록 하다', 'toeic'),
('decade', 'n. 10 년', 'toeic'),
('on-site', 'adj . 현장 의', 'toeic'),
('philanthropic', 'adj . 자선 의', 'toeic'),
('quality time', 'n . ( 가족 / 친구 와 보내는 ) 즐거운 시간', 'toeic'),
('application', 'n . 적용', 'toeic'),
('apply', 'v . 쓰다 . 적용 하다 . 바르다 . 지원 하다 . 신청 하다', 'toeic'),
('applicable', 'ad . 해당 [ 적용 1 되는', 'toeic'),
('organize', 'v . 준비 ( 조직 ] 하다 정리 하다 . 체계화 ( 구조화 ] 하다', 'toeic'),
('manage', 'v . 운영 ( 경영 ] 하다', 'toeic'),
('congratulate', 'v . 축하 하다', 'toeic'),
('survey', 'n . ( 설문 ) 조사 v . ( 설문 ) 조사 하다', 'toeic'),
('entertainment', 'n . 오락', 'toeic'),
('status', 'n . ( 진행 과정 상의 ) 상황', 'toeic'),
('accurate', 'adj . 정확한 정밀한', 'toeic'),
('equipment', 'n . 장비', 'toeic'),
('replacement', 'n . 교체', 'toeic'),
('share', 'v . ( 감정 / 생각 등 을 ) 공유 하다 ( 나누다 ]', 'toeic'),
('conservation', 'n . ( 환경 / 문화재 등 의 ) 보호', 'toeic'),
('conserve', 'v . 보호 하다 . 보존 하다', 'toeic'),
('conservative', 'adj. 보수적인', 'toeic'),
('appreciate', 'v . 감사 하다 . 감상 하다', 'toeic'),
('analyze', 'v . 분석 하다', 'toeic'),
('anniversary', 'n . 기념일', 'toeic'),
('defective', 'adj . 결함 이 있는', 'toeic'),
('institute', 'v . ( 정책 등 을 ) 하다', 'toeic'),
('procedure', 'n . 절차', 'toeic'),
('inconvenience', 'n . 불편 ( 한 것 )', 'toeic'),
('inconvenience', 'n . 불편 ( 한 것 )', 'toeic'),
('inconvenience', 'n . 불편 ( 한 것 )', 'toeic'),
('inconvenient', 'ad . 불편한', 'toeic'),
('summarize', 'v . 요약 하다 . 개괄 하다', 'toeic'),
('announce', 'v . 발표 하다 . 알리다', 'toeic'),
('attend', 'v . 참석 하다', 'toeic'),
('prestigious', 'ad . 명성 있는', 'toeic'),
('prestige', 'n . 명성', 'toeic'),
('upcoming', 'adj . 다가오는', 'toeic'),
('retail', 'adj 소매 의', 'toeic'),
('retailer', 'n . 소매 상인', 'toeic'),
('credit', 'n . 신용 거래', 'toeic'),
('consumer', 'n . 소비자', 'toeic'),
('industry', 'n . 산업', 'toeic'),
('competitive', 'adj . 경쟁력 있는', 'toeic'),
('convenient', 'adj . 편리한 가까운', 'toeic'),
('beverage', 'n . ( 물 이외 의 ) 음료', 'toeic'),
('culinary', 'adj . 요리 의', 'toeic'),
('community', 'n . 지역 사회', 'toeic'),
('present', 'v . ( 영화', 'toeic'),
('production', 'n . ( 영화 등 의 ) 제작', 'toeic'),
('currently', 'adv . 현재', 'toeic'),
('currently', 'adv . 현재', 'toeic'),
('reasonable', 'adi . ( 가격 이 ) 적정한', 'toeic'),
('reservation', 'n . 예약 ( = booking ) : ( 계획 · 생각 에 대한 ) 의구심 [ 거리낌 ]', 'toeic'),
('charity', 'n . 자선 ( 단체 ) ; 구호 기금', 'toeic'),
('identification', 'n . 신분 증명 ( 서 )', 'toeic'),
('publisher', 'n . 출판인', 'toeic'),
('diagnosis', 'n . ( 병원 ) 진단', 'toeic'),
('promptly', 'adv . 지체 없이', 'toeic'),
('container', 'n . 그릇', 'toeic'),
('destructive', 'adj . 파괴 적인', 'toeic'),
('arrange', 'v . 준비 하다 . 마련 하다', 'toeic'),
('productive', 'adj . 생산 적인', 'toeic'),
('administrative', 'adj . 관리 상의', 'toeic'),
('at all times', 'phr . 항상', 'toeic'),
('deduct', 'v . 빼다', 'toeic'),
('insufficient', 'adj 불충분 한', 'toeic'),
('insufficient', 'adj 불충분 한', 'toeic'),
('return', 'v . 돌려 주다 . 반납 하다 . 돌아 오다', 'toeic'),
('revision', 'n . 수정 ( 사항 ) : 수정본', 'toeic'),
('editor', 'n . 편집자', 'toeic'),
('forward', 'v . 보내다 . 전달 하다', 'toeic'),
('delighted', 'adj . 기뻐 하는', 'toeic'),
('impressed', 'adj', 'toeic'),
('attention', 'n . 주의', 'toeic'),
('outstanding', 'adj 뛰어난', 'toeic'),
('attachment', 'n . 부착 : 첨부 ( 파일 )', 'toeic'),
('informative', 'ad . 유익한', 'toeic'),
('strategy', 'n . 전략', 'toeic'),
('post', 'v . ( 안내문 등 을 ) 게시 ( 공고 ] 하다 . 불이다 . ( 편지 / 우편물 을 ) 부치다 . 발송 하다 n . 직책 : 기둥 : 우편 ( 물 )', 'toeic'),
('related', 'adj . 관련 있는', 'toeic'),
('emphasis', 'n . 강조', 'toeic'),
('technician', 'n . 기술자', 'toeic'),
('commemorate', 'v . 기념 하다 . 축하 하다', 'toeic'),
('patronage', 'n . 애용 : 후원', 'toeic'),
('patron', 'n. 고객', 'toeic'),
('supply', 'n . 비품', 'toeic'),
('convenience', 'n . 편의', 'toeic'),
('recipe', 'n . 조리법', 'toeic'),
('hospitality', 'n . 환대 : 친절', 'toeic'),
('transportation', 'n . 운송', 'toeic'),
('popular', 'adj . 인기 있는', 'toeic'),
('artifact', 'n . 인공물', 'toeic'),
('ancient artifacts', '고대 유물', 'toeic'),
('donation', 'n . 기부', 'toeic'),
('unavailable', 'adj . ( 사물 / 사람 이 ) 이용할 수 없는', 'toeic'),
('generosity', 'n . 너그러움', 'toeic'),
('gratitude', 'n . 감사', 'toeic'),
('personal', 'adj . 개인적인', 'toeic'),
('access', 'v . ~ 에 들어가다 . 접근 하다 : 접속 하다 n . 접근 ( 권 )', 'toeic'),
('leave', 'v . 떠나다 : 남기다 . 남겨 두다 : 내버려 두다 . 방치 하다 n', 'toeic'),
('lead', 'v . 지휘 하다', 'toeic'),
('proposal', 'n . 제안 ( 서 )', 'toeic'),
('fill', 'v . ( 일자리 에 사람 을 ) 채우다 ; ( 주문 대로 ) 이행 하다', 'toeic'),
('celebrate', 'v . 기념 하다 . 축하 하다', 'toeic'),
('subscription', 'n . 정기 구독 ( 료 )', 'toeic'),
('independent', 'adj . 독립된', 'toeic'),
('further', 'adj . 더 이상의', 'toeic'),
('blame', 'v . 탓 으로 돌리다', 'toeic'),
('author', 'n', 'toeic'),
('borrow', 'v . 빌리다 . 차용 하다', 'toeic'),
('session', 'n . ( 특정 활동 을 위한 ) 시간', 'toeic'),
('presentation', 'n . 발표', 'toeic'),
('helpful', 'adj . 도움 이 되는', 'toeic'),
('install', 'v . 설치 하다 . ( 프로그램 을 ) 깔다', 'toeic'),
('installment', '할부', 'toeic'),
('installation', 'n . 설치', 'toeic'),
('repair', 'n . 수리', 'toeic'),
('direct', 'v.- 에게 길 을 안내 하다 . 가르쳐 주다 . ( ~ 로 ) 향하게 하다 . ( 편지 등 을 ) 보내다 adj . 직접적인', 'toeic'),
('deposit', 'n . 계약금', 'toeic'),
('perfectly', 'adv . 완전히', 'toeic'),
('valuable', 'adj . 가치 가 큰 : 소중한', 'toeic'),
('furnished', 'adj . 가구 가 비치 된', 'toeic'),
('furnish', 'v . ( 가구 를 ) 비치 하다', 'toeic'),
('expect', 'v . 예기 하다 . 예상 하다', 'toeic'),
('projection', 'n . 예상', 'toeic'),
('keep', 'v . 유지 하다', 'toeic'),
('intriguingly', 'adv . 흥미롭게 도', 'toeic'),
('holder', 'n . 소지자', 'toeic'),
('belong', 'v . ~ 에 소속 하다 . ~ 의 소유물 이다', 'toeic'),
('exhibit', 'n . 전시 ( 회 )', 'toeic'),
('decision', 'n . 결정 : 결단력', 'toeic'),
('decisive', 'adj . 결정적인 : 결단력 있는', 'toeic'),
('bring', 'v . 가져 오다 . 데려 오다', 'toeic'),
('definitely', 'adv . 분명히', 'toeic'),
('progress', 'n . 진행', 'toeic'),
('approve', 'v . 승인 하다 . 인가 하다', 'toeic'),
('welcome', 'adj . 환영 받는 : ~ 해도 좋은 v . 환영 하다 : 기꺼이 받아 들이다 n . 환영', 'toeic'),
('delay', 'v . 미루다', 'toeic'),
('invitation', 'n . 초대 : 초대장', 'toeic'),
('directions', 'n . 방향', 'toeic'),
('positive', 'adj . 긍정적 인', 'toeic'),
('reserve', 'v . 예약 하다 ( -book )', 'toeic'),
('evict', 'v . 쫓아 내다', 'toeic'),
('ownership', 'n . 소유', 'toeic'),
('layout', 'n . 레이아웃', 'toeic'),
('dimension', 'n . 크기', 'toeic'),
('confident', 'adj . 자신감 있는', 'toeic'),
('diligence', 'n . 근면', 'toeic'),
('wind up', 'phr . 결국 - 하게 되다', 'toeic'),
('current', 'adj . 현재 의', 'toeic'),
('experiment', 'v . 시도 하다 . 실험 삼아 해보다 n . ( 과학 적인 ) 실험', 'toeic'),
('ambitious', 'adj . 야심 적인', 'toeic'),
('exclusively', 'adv . 독점적 으로', 'toeic'),
('implement', 'v . 시행 하다 . 이행 하다 n . 연장', 'toeic'),
('paperwork', 'n . 서류 작업', 'toeic'),
('Implement', 'v.- 을 실행 하다', 'toeic'),
('augment', 'v.- 을 증가 시키기다', 'toeic'),
('clement', 'adj. 날씨가 좋은', 'toeic'),
('inclement', 'adj. 날씨가 좋지 않은', 'toeic'),
('subsequent to', 'prep.- 다음 에', 'toeic'),
('agenda', 'n . 안건', 'toeic'),
('brainstorm', 'v . 브레인 스토밍 을 하다 . 자유롭게 생각 하다', 'toeic'),
('advisor', 'n . 고문', 'toeic'),
('join', 'v.- 에 합류 하다 .', 'toeic'),
('collective', 'adj . 축적 된 : 공동 의', 'toeic'),
('excluding', 'prep.- 을 제외 하고', 'toeic'),
('suited', 'adj . 적합한', 'toeic'),
('transaction', 'n . 거래', 'toeic'),
('certain', 'adj . 어떤', 'toeic'),
('lay off', 'phr . ( 정리 ) 해고 하다', 'toeic'),
('lay off', 'phr . ( 정리 ) 해고 하다', 'toeic'),
('lay off', 'phr . ( 정리 ) 해고 하다', 'toeic'),
('need', 'n . 필요', 'toeic'),
('redundancy', 'n . 과잉', 'toeic'),
('redundant', 'adj . 여분 의', 'toeic'),
('repeatedly', 'adv . 되풀이 하여', 'toeic'),
('streamline', 'v . ( 일 / 조직 등 을 ) 간소화 ( 능률화 ] 하다', 'toeic'),
('streamlined', 'adj . 유선형 의 : 능률적 인', 'toeic'),
('yield', 'v . ( 수익 / 결과 등 을 ) 내다 . 산출 하다 n . 산출', 'toeic'),
('flaw', 'n . ( 사물 의 ) 결함', 'toeic'),
('avoid', 'v . 피하다 . 방지 하다', 'toeic'),
('exemplary', 'adj . 모범적 인', 'toeic'),
('informal', 'adj', 'toeic'),
('renowned', 'adj . 유명한', 'toeic'),
('acceptable', 'adj . 받아 들일 수 있는', 'toeic'),
('follow', 'v . 따라 가다 . ( 시간 / 순서 상 ) 뒤를 잇다 ; 주시 하다 ; ( 분명히 ) 이해 하다', 'toeic'),
('terminate', 'v . 끝내다 . 종료 하다', 'toeic'),
('termination', 'n . 종료', 'toeic'),
('private', 'adj . 민간 의', 'toeic'),
('reflective', 'adj . 반영 하는', 'toeic'),
('description', '. n . 서술', 'toeic'),
('place an order', 'phr . 주문 하다', 'toeic'),
('quantity', 'n . 양', 'toeic'),
('stock', 'n . 재고 ( 품 )', 'toeic'),
('warranty', 'n . 보증 ( 서 )', 'toeic'),
('selection', 'n . 선발', 'toeic'),
('accommodation', 'n . 숙박 시설', 'toeic'),
('accommodate', 'v . 숙박 을 제공 하다', 'toeic'),
('assorted', 'adj . 여러 가지 의', 'toeic'),
('assort', 'v . 분류 하다', 'toeic'),
('assortment', 'n . 모듬', 'toeic'),
('ingredient', 'n . ( 요리 ) 재료', 'toeic'),
('spacious', 'adj . 넓은', 'toeic'),
('spacious', 'adj . 넓은', 'toeic'),
('depart', 'v . 떠나다', 'toeic'),
('separate', 'v . 떼어 놓다 : ( 따로 ) 떨어지다 adj . 분리 된 : 독립된', 'toeic'),
('commission', 'n . 수수료', 'toeic'),
('save', 'v . ( 돈 을 ) 모으다', 'toeic'),
('unease', 'n . 불안 ( 감 )', 'toeic'),
('uneasy', 'adj . 불안한', 'toeic'),
('compartment', 'n . 구획', 'toeic'),
('wing', 'n . ( 건물 의 ) 동', 'toeic'),
('enrollment', 'n . 등록', 'toeic'),
('landscape', 'n . 풍경', 'toeic'),
('environment', 'n . 환경', 'toeic'),
('environment', 'n . 환경', 'toeic'),
('conscious', 'adj . 의식 하는', 'toeic'),
('consciousness', 'n . 의식', 'toeic'),
('proficiency', 'n . 숙달', 'toeic'),
('complication', 'n . 복잡한 상태 [ 문제 1 : 합병증', 'toeic'),
('patent', 'v . 특허 를 받다 n . 특허 ( 권 ) ad 특허 의', 'toeic'),
('waste', 'n . 쓰레기', 'toeic'),
('initiative', 'n . 계획 : 진취성', 'toeic'),
('suggestion', 'n . 제안', 'toeic'),
('remove', 'v . 치우다 . 없애다', 'toeic'),
('commuter', 'n . 통근자', 'toeic'),
('vote', 'v . 투표 하다 ; ( 누군가 의 제안 에 ) 동의 하다 n . 투표', 'toeic'),
('frequently', 'adv . 자주', 'toeic'),
('addition', 'n . 추가 ( 된 것 )', 'toeic'),
('assume', 'v . ( 임무 / 역할 / 책임 을 ) 맡다 . 가정 [ 추측', 'toeic'),
('assumption', 'n . 가정 : 인수', 'toeic'),
('assumable', 'adj', 'toeic'),
('object', 'v . 반대 하다', 'toeic'),
('observe', 'v . 관찰 하다 . 주시 하다 준수 하다', 'toeic'),
('observation', 'n . 관찰', 'toeic'),
('observance', 'n . ( 법률 의 ) 준수', 'toeic'),
('observant', 'adj . 관찰력 있는', 'toeic'),
('apologize', 'v . 사과 하다 사죄 하다', 'toeic'),
('indicate', 'v . 나타내 다 . 보여 주다 . 명시 하다', 'toeic'),
('regret', 'v . 유감 스럽게 생각 하다 . 후회 하다 n . 유감', 'toeic'),
('venue', 'n . 개최지', 'toeic'),
('curb', 'v . 억제 하다 . 제한 하다 n . 억제', 'toeic'),
('significantly', 'adv . 상당히', 'toeic'),
('significant', 'adj. 중요한', 'toeic'),
('affect', 'v . 영향 을 미치다 . ( 불리 하게 ) 작용 하다', 'toeic'),
('improve', 'v . 개선 하다', 'toeic'),
('improvement', 'n . 개량', 'toeic'),
('lease', 'n . ( 토지 / 가옥 의 ) 임대차 계약 v . 임대 [ 임차 ] 하다', 'toeic'),
('sculpture', 'n . 조각 ( 품 )', 'toeic'),
('region', 'n . 지역', 'toeic'),
('regional', 'adj . 지방 의', 'toeic'),
('surround', 'v . 둘러 싸다 . 에워 싸다', 'toeic'),
('humble', 'v . 겸허 [ 겸손 ] 하게 하다 adj 검손 한', 'toeic'),
('encourage', 'v . 권장 하다 . 고무 하다', 'toeic'),
('encouragement', 'n . 격려 ( 가 되는 것 )', 'toeic'),
('audience', 'n . 청중', 'toeic'),
('spectator', 'n . 관중', 'toeic'),
('intensive', 'adj . 집중적 인', 'toeic'),
('intensive', 'adj . 집중적 인', 'toeic'),
('intensively', 'adv . 집중적 으로', 'toeic'),
('material', 'n . 재료', 'toeic'),
('acquaint', 'v . 알려주 다', 'toeic'),
('respect', 'n . 존경 ( 심 )', 'toeic'),
('familiarity', 'n . 익숙 함', 'toeic'),
('fit', 'v.- 에 들어 맞다 . 적합 하다 adj . 적합한', 'toeic'),
('invite', 'v . 초대 하다 . 요청 하다', 'toeic'),
('opportunity', 'n . 기회 ( = chance )', 'toeic'),
('always', 'adv . 늘', 'toeic'),
('keep - to a minimum', 'phr.- 을 최소 로 하다', 'toeic'),
('on the downside', '하락세 로', 'toeic'),
('downside', 'n . 불리한 면', 'toeic'),
('resonate', 'v . 반향 을 불러 일으키다', 'toeic'),
('wear', 'n . ( 많이 사용 되어 ) 닮음', 'toeic'),
('worm', 'adj 닮은', 'toeic'),
('weary', 'adj . 지친', 'toeic'),
('novice', 'n . 초보자', 'toeic'),
('haste', 'n . ( 시간 부족 으로 ) 서두름', 'toeic'),
('hastily', 'adv . 서둘러서 [ = hurriedly)', 'toeic'),
('outsell', 'v.- 보다 더 많이 팔리다', 'toeic'),
('alternate', 'adj . 대체 의', 'toeic'),
('blunder', 'n . 실수', 'toeic'),
('fortune', 'n . 재산', 'toeic'),
('principle', 'n . 원리', 'toeic'),
('public speaking', 'phr . 공개 연설', 'toeic'),
('recycled', 'adj . 재활용 된', 'toeic'),
('pledge', 'n . 약속', 'toeic'),
('commendation', 'n . 칭찬', 'toeic'),
('commend', 'v . 칭찬 하다', 'toeic'),
('functionality', 'n . ( 상품 등 의 ) 기능성', 'toeic'),
('function', 'v . 작동 하다 n', 'toeic'),
('functional', 'adj', 'toeic'),
('malfunction', 'v . 오작동 하다 n . 고장', 'toeic'),
('magnify', 'v . 확대 하다', 'toeic'),
('personify', 'v . ~ 를 의인화 하다 ; 전형적 으로 보여 주다 . ~ 의 화신 이다', 'toeic'),
('precaution', 'n . 예방책', 'toeic'),
('inventory', 'n . 재고 ( 품 )', 'toeic'),
('locals', 'n . 지역 주민', 'toeic'),
('upscale', 'adj . 평균 이상의 : 부자 의', 'toeic'),
('intriguing', 'adj', 'toeic'),
('judge', 'v.- 로 미루어 판단 하다 n . 심사 위원', 'toeic'),
('judge', 'v.- 로 미루어 판단 하다 n . 심사 위원', 'toeic'),
('retailer', 'n . 소매업 자', 'toeic'),
('simply', 'adv . 간단히', 'toeic'),
('dine', 'v . 식사 를 하다', 'toeic'),
('tourist', 'n . 관광객', 'toeic'),
('typical', 'adj . 전형적인', 'toeic'),
('virtually', 'adv . 사실상', 'toeic'),
('nursery', 'n . 묘목 장', 'toeic'),
('sapling', 'n . 묘목', 'toeic'),
('wrap up', 'v . 끝내다', 'toeic'),
('exterior', 'n . 외부', 'toeic'),
('interior', 'n . 내부', 'toeic'),
('name', 'v . 명명 하다 . 지명 하다 . 임명 하다 n . 이름 : 평판', 'toeic'),
('personally', 'adv . 직접', 'toeic'),
('domestic', 'adj . 국내 의', 'toeic'),
('domestically', 'adv . 국내 에서', 'toeic'),
('international flights', 'X4', 'toeic'),
('domestic flights', 'HA', 'toeic'),
('market', 'n . 시장', 'toeic'),
('trade', 'n . 무역', 'toeic'),
('acquire', 'v . 습득 하다', 'toeic'),
('consistency', 'n . 한결 같음', 'toeic'),
('increase', 'v . 증가 시키다', 'toeic'),
('increasingly', 'adv . 점점', 'toeic'),
('loyalty', 'n . 충성 ( 심 ) : 충실', 'toeic'),
('merit', 'n . 장점 : 가치 v . 가치 가 있다', 'toeic'),
('versatile', 'adj . 다재 다능 한 다용도 의', 'toeic'),
('growth', 'n . 성장', 'toeic'),
('found', 'v . 설립 하다', 'toeic'),
('propose', 'v . 제안 하다', 'toeic'),
('create', 'v . 창조 하다', 'toeic'),
('periodic', 'adj . 주기 적인', 'toeic'),
('produce', '동사 [ predjú s ] v . 생산 하다 . 제조 하다 명사 [ prádju s l n . 농산물', 'toeic'),
('shortly', 'adv . 곧', 'toeic'),
('attitude', 'n . 태도', 'toeic'),
('mark', 'v . 흔적 을 남기다 . 기념 하다 n . 자국', 'toeic'),
('thought-provoking', 'adj . 시사 하는 바가 많은', 'toeic'),
('unfurnished', 'v . 가구 가 비치 되지 않은', 'toeic'),
('hardware store', '철물점', 'toeic'),
('amenity', 'n . 생활 편의 시설', 'toeic'),
('amenity', 'n . 생활 편의 시설', 'toeic'),
('versatile', 'adj . 다재 다능 한 다용도 의', 'toeic'),
('growth', 'n . 성장', 'toeic'),
('found', 'v . 설립 하다', 'toeic'),
('propose', 'v . 제안 하다', 'toeic'),
('create', 'v . 창조 하다', 'toeic'),
('periodic', 'adj . 주기 적인', 'toeic'),
('period', 'n . 기간', 'toeic'),
('periodically', 'adv . 정기적 으로', 'toeic'),
('periodicals', 'n . 정기 간행물', 'toeic'),
('produce', 'v . 생산 하다 . 제조 하다 명사 n . 농산물', 'toeic'),
('shortly', 'adv . 곧', 'toeic'),
('attitude', 'n . 태도', 'toeic'),
('mark', 'v . 흔적 을 남기다 . 기념 하다 n . 자국', 'toeic'),
('thought-provoking', 'adj . 시사 하는 바가 많은', 'toeic'),
('hardware store', '철물점', 'toeic'),
('unfurnished', 'v . 가구 가 비치 되지 않은', 'toeic'),
('amenity', 'n . 생활 편의 시설', 'toeic'),
('impede', 'v . 방해 하다', 'toeic'),
('succeed', 'v . ( 자리 / 지위 등 ) 뒤를 잇다 . 성공 하다', 'toeic'),
('majority', 'n . 다수', 'toeic'),
('match', 'v . ( 필요 에 ) 맞추다 . 부응 하다 : 어울리다 n . 짝', 'toeic'),
('offer', 'v . 제공 하다 : 제안 하다 n . 제공 : 제안 : 특별 할인가', 'toeic'),
('preferential', 'ad 우선권 ( 특혜 ) 을 주는', 'toeic'),
('publicity', 'n . 홍보', 'toeic'),
('magnify', 'v . 확대 하다', 'toeic'),
('personify', 'v . ~ 를 의인화 하다 ; 전형적 으로 보여 주다 . ~ 의 화신 이다', 'toeic'),
('precaution', 'n . 예방책', 'toeic'),
('inventory', 'n . 재고 ( 품 )', 'toeic'),
('locals', 'n . 지역 주민', 'toeic'),
('upscale', 'adj . 평균 이상의 : 부자 의', 'toeic'),
('intriguing', 'adj', 'toeic'),
('judge', 'v.- 로 미루어 판단 하다 n . 심사 위원', 'toeic'),
('economic', 'adj . 경제 의', 'toeic'),
('derive', 'v.- 에서 비롯 되다 . ~ 에서 나오다', 'toeic'),
('call for', '- 을 필요 로 하다 . 요구 하다', 'toeic'),
('concession stand', 'n . 구내 매점', 'toeic'),
('succinctly', 'adv . 간결 하게', 'toeic'),
('intact', 'adj 온전한', 'toeic'),
('premier', 'n . ( 영화 의 ) 개봉', 'toeic'),
('premier', 'n . ( 영화 의 ) 개봉', 'toeic'),
('resonate', 'v . 반향 을 불러 일으키다', 'toeic'),
('wear', 'n . ( 많이 사용 되어 ) 닮음', 'toeic'),
('novice', 'n . 초보자', 'toeic'),
('haste', 'n . ( 시간 부족 으로 ) 서두름', 'toeic'),
('outsell', 'v.- 보다 더 많이 팔리다 [5. Iterneit)', 'toeic'),
('alternate', 'adj . 대체 의', 'toeic'),
('alternative', 'n . 대안 adj . 대신 하는', 'toeic'),
('blunder', 'n . 실수', 'toeic'),
('fortune', 'n . 재산', 'toeic'),
('principle', 'n . 원리', 'toeic'),
('public speaking', 'phr . 공개 연설', 'toeic'),
('recycled', '재활용 된', 'toeic'),
('pledge', 'n . 약속', 'toeic'),
('commendation', 'n . 칭찬', 'toeic'),
('functionality', 'n . ( 상품 등 의 ) 기능성', 'toeic'),
('additionally', 'adv . 게다가', 'toeic'),
('paralegal', 'n . 준 법률가', 'toeic'),
('tribute', '| n . 헌사', 'toeic'),
('glare', 'n ( 불쾌 하게 ) 환한 빛', 'toeic'),
('glare at-', '- 을 노려 보다', 'toeic'),
('fulfillment', 'n . 이행', 'toeic'),
('correctly', 'adv . 정확하게', 'toeic'),
('experiential', 'adj . 경험 에 의한', 'toeic'),
('preregister', 'v . 사전 등록 하다', 'toeic'),
('conspicuously', 'adv . 눈 에 띄게', 'toeic'),
('flurry', 'n . 눈보라 : ( 잠시 한바탕 벌어지는 ) 부산', 'toeic'),
('lodging', 'n . 임시 숙소', 'toeic'),
('stellar', 'adj . 뛰어난', 'toeic'),
('visibility', 'n . 눈 에 잘 보임', 'toeic'),
('last-minute', 'adj 마지막 순간 의', 'toeic');